name: altair-os
description: Altair OS – immutable system z UX jak macOS/Windows. Gotowy dla użytkowników domowych i deweloperów.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# RPM-y (instalowane do warstwy systemowej)
packages:
  - gnome-software
  - gnome-software-plugin-flatpak
  - gnome-software-plugin-snap
  - gnome-terminal
  - gnome-tweaks
  - firefox
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-good
  - gstreamer1-plugins-base
  - flatpak
  - flatpak-xdg-utils
  - libappstream-glib
  - mimeinfo-cache
  - xdg-utils
  - file-roller
  - nautilus
  - tilix  # alternatywa dla terminala GNOME
  - toolbox
  - dconf-editor
  - langpacks-pl
  - langpacks-en

# Flatpaki preinstalowane (z Flathuba)
flatpaks:
  - org.mozilla.firefox
  - com.github.tchx84.Flatseal
  - com.valvesoftware.Steam
  - org.gnome.Loupe
  - org.gnome.Calculator
  - org.gnome.TextEditor

# Ustawienia środowiska GNOME (opcjonalnie później override w ISO)
gsettings:
  org.gnome.desktop.interface:
    color-scheme: 'prefer-dark'
    gtk-theme: 'Adwaita-dark'
  org.gnome.shell.extensions.dash-to-dock:
    dock-fixed: true
    click-action: 'minimize'

# Dodanie Flathuba jako główne źródło Flatpaków
post-install:
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - update-desktop-database
  - gtk-update-icon-cache

# Skrypty MIME/installerów – opcjonalnie mogą trafić do /usr/share/applications później
mimeapps:
  'application/vnd.flatpak.ref': gnome-software.desktop
  'application/x-flatpakref': gnome-software.desktop
  'x-scheme-handler/flatpakref': gnome-software.desktop

# Dodatki systemowe
extensions:
  - user-theme
  - appindicator
  - dash-to-dock

# App Center branding – dodanie własnych ikon, opisów, metadanych (do rozwoju później)
branding:
  wallpaper: /usr/share/backgrounds/altair-wallpaper.jpg
  icon-theme: Adwaita
  cursor-theme: Adwaita

# Tagowanie wersji
labels:
  variant: home
  version: "1.0"
  os: altair
